### ISSUE TITLE
atrcopy dependency broken

### ISSUE THREAD

**Issue by marianodominguez** [robmcmullen/omnivore#255]
In python 2.7, it tries to install latest atrcopy, since 7.0. It requires 3.6

in order to fix it , I installed an older version first.

pip install atrcopy==6.5.0

**Comment by robmcmullen** [comment]
This is "fixed" in two ways: Omnivore doesn't require atrcopy any more, and it requires python 3. I've abandoned python 2 now, so unfortunately for this particular issue it's as fixed as it's going to get. Hopefully you can move to python 3.
