### ISSUE TITLE
libudis Missing stringify_udis_cpu.h

### ISSUE THREAD

**Issue by TikiBill** [robmcmullen/omnivore#257]
stringify_udis_cpu.c calls out stringify_udis_cpu.h, but that header file is missing, preventing omnivore from building from a clean git pull. 

It does seem the file is not particularly critical because creating an empty file allows the libudis build to work, and for some reason the file is also specified in .gitignore.

And thank you for omnivore! I appreciate it and the work you've put into it.

**Comment by TikiBill** [comment]
After working around a few other build issues, it seems that perhaps the real issue is that `disasm_gen.py` is missing:

```shell
Bill@tiki MINGW64 ~/Code/external/omnivore/libudis (master)
$ ./rebuild_all.sh
processing udis\6502.py
processing udis\65816.py
processing udis\65c02.py
processing udis\6800.py
processing udis\6809.py
processing udis\6811.py
processing udis\8051.py
processing udis\8080.py
processing udis\z80.py
processing custom_cpus\jumpman_level.py
C:\Opt\Python36\python.exe: can't open file 'disasm_gen.py': [Errno 2] No such file or directory
C:\Users\Bill\Code\external\omnivore\libudis\disasm_info.pyx
```

**Comment by robmcmullen** [comment]
I made a mistake and began working on new features in the master branch, which is where I left it for months as I've not had time to work on it. If you rebase to an earlier commit, you should be able to build it correctly:

git reset --hard debaed943

**Comment by robmcmullen** [comment]
I'm going to do a force push to reset the master branch back to commit debaed9 so other people won't have that problem. Once you do the git reset, you shouldn't have to pull again.

**Comment by robmcmullen** [comment]
Now, let me check into the missing disasm_gen.py file from a clean pull and I'll let you know.

**Comment by robmcmullen** [comment]
A clean checkout built correctly for me (on linux, anyway) when I started from the new master. I don't have a current windows setup, so I'll look into it once I get a virtual machine going.

**Comment by TikiBill** [comment]
Thanks!

It does seem there are some issues present in a windows build not in the Linux build. A clean pull does mostly (besides the missing header file) fully build in Linux for me as well. I'll work on the Windows issues (I miss having Linux as my primary desktop) and submit some pull requests as I figure out issues.

Or I'll just boot into Linux and focus on Jumpman levels there.

Thanks again. Feel free to close this as resolved.

**Comment by robmcmullen** [comment]
Great, I'll close this and will look at your new issues.
