### ISSUE TITLE
Starting address for disassembly

### ISSUE THREAD

**Issue by option8** [robmcmullen/omnivore#88]
Is it possible to set the starting address for disassembled code, so that, for instance, a disassembled ROM can start at $F000 instead of $0000?

**Comment by robmcmullen** [comment]
Choose the segment you want in the Segments list and then use the Disk Image -> Set Segment Origin menu item to set the start value of $F000

**Comment by option8** [comment]
Ah. I'll have to create a segment first, then. I was trying that, but
hadn't created any segments - I was trying to set the start address for the
whole thing.

**Comment by robmcmullen** [comment]
I think this is pretty much fixed. You can set an origin on any segment now.

**Comment by robmcmullen** [comment]
The 1.0 release should be out this week.
